create sequence account_settings_seq start with 1 increment by 50;
create sequence accounts_seq start with 1 increment by 50;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
create sequence account_settings_seq start with 1 increment by 50;
create sequence accounts_seq start with 1 increment by 50;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
create sequence account_settings_seq start with 1 increment by 50;
create sequence accounts_seq start with 1 increment by 50;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
create sequence account_settings_seq start with 1 increment by 50;
create sequence accounts_seq start with 1 increment by 50;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
create sequence account_settings_seq start with 1 increment by 50;
create sequence accounts_seq start with 1 increment by 50;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
create table account_settings (account_id bigint not null, id bigint not null, name varchar(255) not null, value varchar(255) not null, primary key (id));
create table accounts (id bigint not null, name varchar(100) not null, email_address varchar(255), primary key (id));
alter table if exists account_settings add constraint FK54uo82jnot7ye32pyc8dcj2eh foreign key (account_id) references accounts;
